version: '3.8'

services:
  produtividade:
    build:
      context: .
      args:
        - DATABASE_URL=${DATABASE_URL}
    container_name: produtividade
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - DATABASE_URL=${DATABASE_URL}
      - PUBLIC_KEY=${PUBLIC_KEY}
      - PORT=${PORT:-4000}
    # A seção 'ports' foi removida. Traefik gerencia o acesso externo.
    networks:
      - proxy
    labels:
      # --- Habilita o Traefik para este serviço ---
      - "traefik.enable=true"
      - "traefik.http.routers.produtividade.rule=Host(`${PRODUTIVIDADE_HOST}`)"
      - "traefik.http.routers.produtividade.service=produtividade"
      - "traefik.http.routers.produtividade.tls.certresolver=letsencrypt"
      - "traefik.http.services.produtividade.loadbalancer.server.port=4000"

networks:
  proxy:
    external: true
    # Simplifiquei a declaração da rede. O nome usado no serviço é o mesmo da rede externa.